const GET_DIRECTORS = "GET_DIRECTORS";
const GET_DIRECTORS_WITH_ID = "GET_DIRECTORS_WITH_ID";
const SEARCH_DIRECTOR = "SEARCH_DIRECTOR";

export { GET_DIRECTORS, GET_DIRECTORS_WITH_ID, SEARCH_DIRECTOR };
