const GET_MOVIES = "GET_MOVIES";
const GET_MOVIES_WITH_ID = "GET_MOVIES_WITH_ID";
const SEARCH_MOVIE = "SEARCH_MOVIE";
const ADD_MOVIE = "ADD_MOVIE";
const REMOVE_MOVIE = "REMOVE_MOVIE";
const SEEN_MOVIE = "SEEN_MOVIE";
const UNSEEN_MOVIE = "UNSEEN_MOVIE";

export {
  GET_MOVIES,
  GET_MOVIES_WITH_ID,
  SEARCH_MOVIE,
  ADD_MOVIE,
  REMOVE_MOVIE,
  SEEN_MOVIE,
  UNSEEN_MOVIE,
};
